### ISSUE TITLE
Inquiry about adaptive bandwidth KDE

### ISSUE THREAD

**Issue by jcibanezm** [WEC-Sim/WDRT#13]
Hi, 
I was looking at a presentation about Kernel Density Estimation (KDE) with adaptive bandwidth 
selection for environmental contours of extreme sea state, from about two years ago. I was wondering if the features described in the presentation are already included in WDRT, as I have been looking for them but can not find them. If they are not available yet, I wanted to ask if they will be available in the future and roughly how long would it take.

All the best,
Juan

**Comment by nevmart** [comment]
Hi Juan,

Thanks for your interest in the WDRT. We have moved away from using KDE with adaptive bandwidth selection, primarily because the resulting contour is sensitive to the choice of the pilot bandwidth and it can be computationally expensive. However, we are working on implementing a method for calculating contours using KDE with a fixed bandwidth. This will also have the option to take a log transformation of the data prior to fitting the KDE, which can be useful when using a fixed bandwidth if the data are naturally positive. We are planning on having a public release of the code that contains the KDE contours within the next five months. If you have any other questions, please let us know.

Thank you!

Nevin

**Comment by rgcoe** [comment]
Juan - We've included some KDE prediction methods in the latest commit if you're interested: 5b80f76ba6a155b597cf0e65f3e98311f6cdf89d
