### ISSUE TITLE
Breaking steepness based on Hm0

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#17]
Hi WDRT Team,

I'm revisiting the steepness limitation on the environmental contours in ESSC.py. The default max ratio of Hm0/L in ESSC is 0.07. The wavelength, L is presumably going to be based on Te or Ta in these examples. Using this limit, the breaking limit follows the data very nicely in some cases. For example, here's data for CDIP160 with the steepness-limited PCA contour from WDRT:
![image](https://user-images.githubusercontent.com/12396856/48867969-03dd7800-eda6-11e8-87dc-7fd76359644b.png)

However, I'm having trouble justifying the the 0.07 limit. For regular waves in deep water, of course, waves break near H/L = 0.14. It seems almost coincidence, then, that the 0.07 limit fits the data. 

Any references or thoughts on how you arrived at that limit?

Thanks,
Toby.

**Comment by aubreyeckert** [comment]
Hi @Toby-D,

The 0.7 value is derived from from DNV-RP-C205 (DNV recommended practice on environmental conditions and loads), which gives the empirical limit for significant steepness based on data from the Norwegian Continental Shelf. Here is the link to the standard:

https://rules.dnvgl.com/docs/pdf/dnv/codes/docs/2010-10/rp-c205.pdf

Note that the steepness calculation in the WDRT was originally included in the ESSC Matlab code available here:

https://energy.sandia.gov/energy/renewable-energy/water-power/resource-characterization/extreme-sea-state-contour/

The max ratio is left as a user input so that this value can be changed if the assumptions do not fit the location at which you are calculating the steepness. Let us know if you have any further questions on this.

Thanks,
Aubrey

**Comment by Toby-D** [comment]
OK, thanks Aubrey!

**Comment by ssolson** [comment]
I suggest adding Aubrey's reference to the default value in ESSC.py and closing this issue.
