### ISSUE TITLE
Does not run: example_MLER_testrun.py

### ISSUE THREAD

**Issue by ssolson** [WEC-Sim/WDRT#34]
The ` example_MLER_testrun.py` fails at line 23  Test.MLERcoeffsGen(3,1.0) because:

*** TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

The data directories were modified to use the local data. This should probably be the default:

```python
RAOdir      = r'data/RAO_data'
outputDir   = '.'
```

**Comment by zmorrell-sand** [comment]
I have found the fix for the type error and gotten the function to run successfully. On line 39 of spectrum.py, the third argument in linspace needs to be cast to an int. I also included an np.ceil() call to make sure that there is no loss of precision from rounding.  I will push this later with a fix for issues 35 and 29.

As far as default directories are concerned, I am inclined to agree with you that the WDRT should likely use relative paths for the example functions so that new users don't have to open up the file and modify the path for every example they want to run.
