### ISSUE TITLE
"Could not find data for CDIP site: ___"

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#7]
@ryancoe and team, I've been playing around with WDRT, and it seems like an awesome tool! 

I'm hitting a bug when I try to fetch CDIP data: If I modify example_envSampling.py to load a CDIP buoy,
`buoy160 = ESSC.Buoy('160','CDIP')`,
I get the error:
"IOError: Could not find data for CDIP site: 160"

If I manually point a browser to the specified URL, the .nc file begins downloading. But I don't see where that URL is supposed to be called in the ESSC script, and it doesn't seem to attempt to download anything. 

Thanks,

Toby.

Details: 
Running Python 2.7 on Windows 10
Pulled from remote repo on 10/23/2017

**Comment by tyleresterly** [comment]
Hi @Toby-D ,
The problem seemed to be that somehow the line of code that actually downloaded the data was deleted in a past commit (most likely due to some sort of mistake in a branch-merge). The code has been re-updated, so if you pull again the example you gave should work as expected now.

Sorry for the trouble and thanks for bringing this to our attention!


Thanks,
Tyler

**Comment by Toby-D** [comment]
Thanks Tyler, that makes a lot more sense now :)
