### ISSUE TITLE
Use joint probability distribution tables as input to ESSC?

### ISSUE THREAD

**Issue by Toby-D** [WEC-Sim/WDRT#9]
@ryancoe and @aubreyeckert ,

I'm thinking about whether ESSC.py could be modified to calculate extreme contours using a joint probability distribution table (e.g. significant wave height versus peak period) as an input instead of a list of all the observed combinations of H and T.  Sometimes these tables are available when the full historical data is not. I expect that the resolution, or smoothness, of the resulting contour would be limited by the resolution of the probability table. Besides that, can you think of any reason why that approach wouldn't work?

Thanks,

Toby.

**Comment by aubreyeckert** [comment]
Hello @Toby-D,

I am not sure if we follow fully. Can you send an example of the joint probability distribution table that you are describing? A large portion of generating extreme contours is constructing this joint probability distribution describing sea state variables. This also differentiates many of the contour methods in the literature and those available in the WDRT. If there is already a joint probability distribution defined for a data set, I am not sure if using this as input to a method that generates a different joint probability distribution would make sense. Have you seen this done before? If so, can you send examples?

Thanks,
Aubrey

**Comment by Toby-D** [comment]
Thanks for the reply, Aubrey. 

My terminology probably wasn't the most descriptive. When I talk about joint probability distribution tables, I just mean a table showing the frequency of occurrence of each combination of T and Hs, which is obtained by simply sorting the historical data into bins. For example, the way NOAA presents these is:

![image](https://user-images.githubusercontent.com/12396856/34741071-81c4200c-f54f-11e7-983c-870df6947d2c.png)

**Comment by aubreyeckert** [comment]
Hello @Toby-D,

Apologies for the delayed response. It is possible to use a joint probability distribution (JPD) table, such as the one you show, to create extreme sea state contours. However, using the full set of available data, instead of pre-processing it into bins, is more ideal.

The JPD table is a coarse representation of the empirical multivariate density function. When we use, for instance, the PCA contour method, we first construct an estimate of this density function using a marginal distribution fit for one variable and then distribution fits on binned values of the second variable to make these distributions conditional on the first variable. We can then calculate the contour using these marginal distributions and their relationship. It would be convoluted to first assume that we have an estimate of the density (the JPD table) that we then transform to a different estimate of the density before calculating the contour.

Instead, calculating a contour using the JPD table would require a different method – the density is represented differently and would need to be evaluated differently. As you said, the result of this would depend on the resolution of the table.

-Aubrey

**Comment by Toby-D** [comment]
Thanks Aubrey! That makes sense, and helps clarify it for me.

Toby.
